

pengwifi-objs = ker.o

obj-m := pengwifi.o

default:
	make -C $(KERNEL_DIR) M=$(shell pwd) CROSS_COMPILE=$(CROSS_COMPILE)

clean:
	rm -rf *.o *.ko *.mod.c .*.cmd *.markers *.order *.symvers .tmp_versions	
