#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99
#BIN=/ezwrt/ezwrt_daemon.lua
BIN=/ezwrt/dmwatch
RUN_D=/var/run
#PID_F=$RUN_D/$BIN.pid

start() {
	uci set network.lan.proto=dhcp
	uci set network.lan.ipaddr='192.168.10.1'
	uci set network.lan.netmask='255.255.255.0'
	uci set network.wan.proto=static
	uci set firewall.@zone[0].input=ACCEPT
	uci set dhcp.lan.ignore=1
	uci commit
	/etc/init.d/network restart
	/etc/init.d/firewall restart
	/etc/init.d/dhcp restart
	rmmod pengwifi
	insmod /lib/modules/pengwifi.ko	
	killall pwf
	pwf -r 60.206.36.144 -f &
}

stop() {
	echo ""
}

